import {
  BadgePercent,
  BriefcaseBusiness,
  CalendarClock,
  CreditCard,
  Grid2X2,
  HardHat,
  IdCard,
  KeyRound,
  Layers3,
  ListChecks,
  MapPinned,
  MonitorCog,
  PackageCheck,
  ShieldCheck,
  SlidersHorizontal,
  TicketPercent,
  UsersRound,
} from 'lucide-react'
import type { ResourceConfig } from './resource.types'

export const resourceConfigs: ResourceConfig[] = [
  {
    key: 'roles',
    title: 'Roles',
    description: 'Role master with precedence and dashboard privilege level.',
    endpoint: '/api/roles',
    route: '/roles',
    idField: 'iMasterId',
    screenCode: 'ROLES',
    permissionCodeBase: 'ROLES',
    icon: ShieldCheck,
    group: 'Access',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'precedence', label: 'Precedence' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Role code', type: 'string', required: true, placeholder: 'OPS_MANAGER' },
      { name: 'sName', label: 'Role name', type: 'string', required: true, placeholder: 'Ops Manager' },
      { name: 'precedence', label: 'Precedence', type: 'number', required: true },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'user-types',
    title: 'User Types',
    description: 'Customer, hero, dashboard staff, and other account classifications.',
    endpoint: '/api/user-types',
    route: '/user-types',
    idField: 'iMasterId',
    screenCode: 'USER_TYPES',
    permissionCodeBase: 'USER_TYPES',
    icon: UsersRound,
    group: 'Access',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'User type code', type: 'string', required: true, placeholder: 'DASHBOARD' },
      { name: 'sName', label: 'User type name', type: 'string', required: true, placeholder: 'Dashboard User' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'screens',
    title: 'Screens',
    description: 'Dashboard sections/screens used to build the frontend menu.',
    endpoint: '/api/screens',
    route: '/screens',
    idField: 'iMasterId',
    screenCode: 'SCREENS',
    permissionCodeBase: 'SCREENS',
    icon: MonitorCog,
    group: 'Access',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'routePath', label: 'Route' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Screen code', type: 'string', required: true, placeholder: 'BOOKINGS' },
      { name: 'sName', label: 'Screen name', type: 'string', required: true, placeholder: 'Bookings' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'routePath', label: 'Route path', type: 'string', placeholder: '/bookings' },
      { name: 'parentScreenId', label: 'Parent screen ID', type: 'number' },
      { name: 'displayOrder', label: 'Display order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'permissions',
    title: 'Permissions',
    description: 'Action permissions such as VIEW, CREATE, UPDATE, DELETE, EXPORT, ASSIGN.',
    endpoint: '/api/permissions',
    route: '/permissions',
    idField: 'iMasterId',
    screenCode: 'PERMISSIONS',
    permissionCodeBase: 'PERMISSIONS',
    icon: KeyRound,
    group: 'Access',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'description', label: 'Description' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Permission code', type: 'string', required: true, placeholder: 'BOOKINGS_VIEW' },
      { name: 'sName', label: 'Permission name', type: 'string', required: true, placeholder: 'Bookings View' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-categories',
    title: 'Service Categories',
    description: 'Top-level grouping for bookable marketplace services.',
    endpoint: '/api/service-categories',
    route: '/service-categories',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: Grid2X2,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'displayOrder', label: 'Order' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Category code', type: 'string', required: true },
      { name: 'sName', label: 'Category name', type: 'string', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'displayOrder', label: 'Display order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-types',
    title: 'Service Types',
    description: 'Reusable service type definitions used by services.',
    endpoint: '/api/service-types',
    route: '/service-types',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: Layers3,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Type code', type: 'string', required: true },
      { name: 'sName', label: 'Type name', type: 'string', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'services',
    title: 'Services',
    description: 'Bookable services with pricing, tax, duration, and media rules.',
    endpoint: '/api/services',
    route: '/services',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: PackageCheck,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'basePrice', label: 'Base', format: 'currency' },
      { key: 'salePrice', label: 'Sale', format: 'currency' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'iServiceCategoryMasterId', label: 'Category ID', type: 'number', required: true },
      { name: 'iServiceTypeMasterId', label: 'Service type ID', type: 'number', required: true },
      { name: 'sCode', label: 'Service code', type: 'string', required: true },
      { name: 'sName', label: 'Service name', type: 'string', required: true },
      { name: 'shortDescription', label: 'Short description', type: 'string' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'basePrice', label: 'Base price', type: 'number', required: true },
      { name: 'salePrice', label: 'Sale price', type: 'number' },
      { name: 'taxPercentage', label: 'Tax %', type: 'number' },
      { name: 'estimatedDurationMinutes', label: 'Duration minutes', type: 'number', required: true },
      { name: 'minQuantity', label: 'Min quantity', type: 'number' },
      { name: 'maxQuantity', label: 'Max quantity', type: 'number' },
      { name: 'isSlotRequired', label: 'Slot required', type: 'boolean' },
      { name: 'isSubscriptionEligible', label: 'Subscription eligible', type: 'boolean' },
      { name: 'requiresBeforeImage', label: 'Requires before image', type: 'boolean' },
      { name: 'requiresAfterImage', label: 'Requires after image', type: 'boolean' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-slots',
    title: 'Service Slots',
    description: 'Booking windows and slot capacity.',
    endpoint: '/api/service-slots',
    route: '/service-slots',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: CalendarClock,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'slotName', label: 'Slot' },
      { key: 'startTime', label: 'Start' },
      { key: 'endTime', label: 'End' },
      { key: 'maxBookings', label: 'Capacity' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'iServiceMasterId', label: 'Service ID', type: 'number', allowEmpty: true },
      { name: 'slotName', label: 'Slot name', type: 'string', required: true },
      { name: 'startTime', label: 'Start time', type: 'time', required: true },
      { name: 'endTime', label: 'End time', type: 'time', required: true },
      { name: 'maxBookings', label: 'Max bookings', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'coupons',
    title: 'Coupons',
    description: 'Promo codes, validity windows, and usage limits.',
    endpoint: '/api/coupons',
    route: '/coupons',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: TicketPercent,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'sCode', label: 'Code' },
      { key: 'sName', label: 'Name' },
      { key: 'discountType', label: 'Type' },
      { key: 'discountValue', label: 'Value' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'sCode', label: 'Coupon code', type: 'string', required: true },
      { name: 'sName', label: 'Coupon name', type: 'string', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'discountType',
        label: 'Discount type',
        type: 'enum',
        required: true,
        options: [
          { label: 'Percentage', value: 'PERCENTAGE' },
          { label: 'Flat', value: 'FLAT' },
        ],
      },
      { name: 'discountValue', label: 'Discount value', type: 'number', required: true },
      { name: 'maxDiscountAmount', label: 'Max discount', type: 'number' },
      { name: 'minOrderAmount', label: 'Min order', type: 'number' },
      { name: 'startAt', label: 'Start date', type: 'date', required: true },
      { name: 'endAt', label: 'End date', type: 'date', required: true },
      { name: 'usageLimit', label: 'Usage limit', type: 'number' },
      { name: 'perUserLimit', label: 'Per user limit', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'subscriptions',
    title: 'Subscriptions',
    description: 'Customer subscription records and lifecycle status.',
    endpoint: '/api/subscriptions',
    route: '/subscriptions',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: BadgePercent,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iCustomerUserMasterId', label: 'Customer' },
      { key: 'iSubscriptionTypeMasterId', label: 'Plan' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'startAt', label: 'Start', format: 'date' },
      { key: 'endAt', label: 'End', format: 'date' },
    ],
    fields: [
      { name: 'iSubscriptionTypeMasterId', label: 'Subscription type ID', type: 'number', required: true },
      { name: 'iCustomerUserMasterId', label: 'Customer user ID', type: 'number', required: true },
      { name: 'startAt', label: 'Start date', type: 'date', required: true },
      { name: 'endAt', label: 'End date', type: 'date', required: true },
      {
        name: 'status',
        label: 'Status',
        type: 'enum',
        options: [
          { label: 'Active', value: 'ACTIVE' },
          { label: 'Paused', value: 'PAUSED' },
          { label: 'Cancelled', value: 'CANCELLED' },
          { label: 'Expired', value: 'EXPIRED' },
        ],
      },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'hero-profiles',
    title: 'Hero Profiles',
    description: 'Worker/hero operational profile, availability, rating, and worker state.',
    endpoint: '/api/hero-profiles',
    route: '/hero-profiles',
    idField: 'iMasterId',
    screenCode: 'USERS',
    permissionCodeBase: 'USERS',
    icon: HardHat,
    group: 'People',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iUserMasterId', label: 'User ID' },
      { key: 'heroCode', label: 'Hero code' },
      { key: 'workerState', label: 'State', format: 'status' },
      { key: 'averageRating', label: 'Rating' },
      { key: 'isAvailable', label: 'Available', format: 'boolean' },
    ],
    fields: [
      { name: 'iUserMasterId', label: 'User ID', type: 'number', required: true },
      { name: 'heroCode', label: 'Hero code', type: 'string', required: true },
      { name: 'governmentIdNumber', label: 'Government ID', type: 'string' },
      { name: 'skillSummary', label: 'Skill summary', type: 'textarea' },
      { name: 'averageRating', label: 'Average rating', type: 'number' },
      { name: 'totalRatings', label: 'Total ratings', type: 'number' },
      { name: 'isAvailable', label: 'Available', type: 'boolean' },
    ],
  },
  {
    key: 'customer-profiles',
    title: 'Customer Profiles',
    description: 'Customer profile records and marketplace rating data.',
    endpoint: '/api/customer-profiles',
    route: '/customer-profiles',
    idField: 'iMasterId',
    screenCode: 'USERS',
    permissionCodeBase: 'USERS',
    icon: IdCard,
    group: 'People',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iUserMasterId', label: 'User ID' },
      { key: 'customerCode', label: 'Customer code' },
      { key: 'averageRating', label: 'Rating' },
      { key: 'totalRatings', label: 'Reviews' },
    ],
    fields: [
      { name: 'iUserMasterId', label: 'User ID', type: 'number', required: true },
      { name: 'customerCode', label: 'Customer code', type: 'string', required: true },
      { name: 'averageRating', label: 'Average rating', type: 'number' },
      { name: 'totalRatings', label: 'Total ratings', type: 'number' },
    ],
  },
  {
    key: 'employee-profiles',
    title: 'Employee Profiles',
    description: 'Internal employee profile records.',
    endpoint: '/api/employee-profiles',
    route: '/employee-profiles',
    idField: 'iMasterId',
    screenCode: 'USERS',
    permissionCodeBase: 'USERS',
    icon: BriefcaseBusiness,
    group: 'People',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iUserMasterId', label: 'User ID' },
      { key: 'employeeCode', label: 'Employee code' },
      { key: 'designation', label: 'Designation' },
      { key: 'department', label: 'Department' },
    ],
    fields: [
      { name: 'iUserMasterId', label: 'User ID', type: 'number', required: true },
      { name: 'employeeCode', label: 'Employee code', type: 'string', required: true },
      { name: 'designation', label: 'Designation', type: 'string' },
      { name: 'department', label: 'Department', type: 'string' },
    ],
  },
  {
    key: 'booking-assignments',
    title: 'Assignments',
    description: 'Hero assignment records attached to bookings.',
    endpoint: '/api/booking-assignments',
    route: '/assignments',
    idField: 'iTransId',
    screenCode: 'ASSIGNMENTS',
    permissionCodeBase: 'ASSIGNMENTS',
    icon: ListChecks,
    group: 'Operations',
    columns: [
      { key: 'iTransId', label: 'ID' },
      { key: 'iBookingTransId', label: 'Booking' },
      { key: 'iHeroUserMasterId', label: 'Hero' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'assignedAt', label: 'Assigned', format: 'datetime' },
    ],
    fields: [
      { name: 'iBookingTransId', label: 'Booking ID', type: 'number', required: true },
      { name: 'iHeroUserMasterId', label: 'Hero user ID', type: 'number', required: true },
      { name: 'assignedAt', label: 'Assigned at', type: 'date' },
      {
        name: 'status',
        label: 'Status',
        type: 'enum',
        options: [
          { label: 'Assigned', value: 'ASSIGNED' },
          { label: 'Accepted', value: 'ACCEPTED' },
          { label: 'Started', value: 'STARTED' },
          { label: 'Completed', value: 'COMPLETED' },
          { label: 'Cancelled', value: 'CANCELLED' },
        ],
      },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
    ],
  },
  {
    key: 'payments',
    title: 'Payments',
    description: 'Payment records, gateway identifiers, status, and reconciliation data.',
    endpoint: '/api/payments',
    route: '/payments',
    idField: 'iTransId',
    screenCode: 'PAYMENTS',
    permissionCodeBase: 'PAYMENTS',
    icon: CreditCard,
    group: 'Money',
    columns: [
      { key: 'iTransId', label: 'ID' },
      { key: 'iBookingTransId', label: 'Booking' },
      { key: 'provider', label: 'Provider' },
      { key: 'amount', label: 'Amount', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'paidAt', label: 'Paid at', format: 'datetime' },
    ],
    fields: [
      { name: 'iBookingTransId', label: 'Booking ID', type: 'number', required: true },
      { name: 'paidByUserMasterId', label: 'Paid by user ID', type: 'number', required: true },
      { name: 'provider', label: 'Provider', type: 'string', required: true },
      { name: 'providerPaymentId', label: 'Provider payment ID', type: 'string' },
      { name: 'providerOrderId', label: 'Provider order ID', type: 'string' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'currency', label: 'Currency', type: 'string', placeholder: 'INR' },
      { name: 'status', label: 'Status', type: 'string', required: true },
      { name: 'paymentMethod', label: 'Method', type: 'string' },
      { name: 'paidAt', label: 'Paid at', type: 'date' },
    ],
  },
  {
    key: 'hero-service-areas',
    title: 'Hero Service Areas',
    description: 'Hero location coverage by city, pincode, and radius.',
    endpoint: '/api/hero-service-areas',
    route: '/hero-service-areas',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: MapPinned,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iHeroUserMasterId', label: 'Hero' },
      { key: 'city', label: 'City' },
      { key: 'pincode', label: 'Pincode' },
      { key: 'radiusKm', label: 'Radius KM' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'iHeroUserMasterId', label: 'Hero user ID', type: 'number', required: true },
      { name: 'city', label: 'City', type: 'string' },
      { name: 'state', label: 'State', type: 'string' },
      { name: 'pincode', label: 'Pincode', type: 'string' },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'radiusKm', label: 'Radius KM', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'hero-service-mappings',
    title: 'Hero Service Mappings',
    description: 'Which heroes can perform which services.',
    endpoint: '/api/hero-service-mappings',
    route: '/hero-service-mappings',
    idField: 'iMasterId',
    screenCode: 'SERVICES',
    permissionCodeBase: 'SERVICES',
    icon: SlidersHorizontal,
    group: 'Services',
    columns: [
      { key: 'iMasterId', label: 'ID' },
      { key: 'iHeroUserMasterId', label: 'Hero' },
      { key: 'iServiceMasterId', label: 'Service' },
      { key: 'isActive', label: 'Status', format: 'boolean' },
    ],
    fields: [
      { name: 'iHeroUserMasterId', label: 'Hero user ID', type: 'number', required: true },
      { name: 'iServiceMasterId', label: 'Service ID', type: 'number', required: true },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
]

export const resourceConfigByKey = new Map(resourceConfigs.map((config) => [config.key, config]))

export const findResourceByRoute = (route: string): ResourceConfig | undefined =>
  resourceConfigs.find((config) => config.route === route)
