import type { MasterConfig } from './masters.types'

export const masterConfigs: MasterConfig[] = [
  {
    key: 'roles',
    title: 'Roles',
    description: 'Role master with precedence and access position.',
    endpoint: '/api/roles',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'Role code', type: 'string', required: true, placeholder: 'ROLE_MANAGER' },
      { name: 'sName', label: 'Role name', type: 'string', required: true, placeholder: 'Manager' },
      { name: 'precedence', label: 'Precedence', type: 'number', required: true },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'user-types',
    title: 'User Types',
    description: 'Employee, hero, customer and future user classifications.',
    endpoint: '/api/user-types',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'User type code', type: 'string', required: true, placeholder: 'CUSTOMER' },
      { name: 'sName', label: 'User type name', type: 'string', required: true, placeholder: 'Customer' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-categories',
    title: 'Service Categories',
    description: 'Top-level grouping for services.',
    endpoint: '/api/service-categories',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'Category code', type: 'string', required: true, placeholder: 'HOME_CLEANING' },
      { name: 'sName', label: 'Category name', type: 'string', required: true, placeholder: 'Home Cleaning' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'displayOrder', label: 'Display order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-types',
    title: 'Service Types',
    description: 'Cleaning, maintenance, pest control and other service modes.',
    endpoint: '/api/service-types',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'Service type code', type: 'string', required: true, placeholder: 'CLEANING' },
      { name: 'sName', label: 'Service type name', type: 'string', required: true, placeholder: 'Cleaning' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'services',
    title: 'Services',
    description: 'Bookable services with pricing, quantity and image requirements.',
    endpoint: '/api/services',
    idField: 'iMasterId',
    fields: [
      {
        name: 'iServiceCategoryMasterId',
        label: 'Service category',
        type: 'select',
        required: true,
        optionSource: 'service-categories',
      },
      {
        name: 'iServiceTypeMasterId',
        label: 'Service type',
        type: 'select',
        required: true,
        optionSource: 'service-types',
      },
      { name: 'sCode', label: 'Service code', type: 'string', required: true, placeholder: 'WATER_TANK_CLEANING' },
      { name: 'sName', label: 'Service name', type: 'string', required: true, placeholder: 'Water Tank Cleaning' },
      { name: 'shortDescription', label: 'Short description', type: 'string' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'basePrice', label: 'Base price', type: 'number', required: true },
      { name: 'salePrice', label: 'Sale price', type: 'number' },
      { name: 'taxPercentage', label: 'Tax %', type: 'number' },
      { name: 'estimatedDurationMinutes', label: 'Duration minutes', type: 'number', required: true },
      { name: 'minQuantity', label: 'Minimum quantity', type: 'number' },
      { name: 'maxQuantity', label: 'Maximum quantity', type: 'number' },
      { name: 'isSlotRequired', label: 'Slot required', type: 'boolean' },
      { name: 'isSubscriptionEligible', label: 'Subscription eligible', type: 'boolean' },
      { name: 'requiresBeforeImage', label: 'Requires before image', type: 'boolean' },
      { name: 'requiresAfterImage', label: 'Requires after image', type: 'boolean' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-slots',
    title: 'Service Slots',
    description: 'Booking time windows and slot capacity.',
    endpoint: '/api/service-slots',
    idField: 'iMasterId',
    fields: [
      {
        name: 'iServiceMasterId',
        label: 'Specific service',
        type: 'select',
        optionSource: 'services',
        allowEmpty: true,
      },
      { name: 'slotName', label: 'Slot name', type: 'string', required: true, placeholder: 'Morning Slot' },
      { name: 'startTime', label: 'Start time', type: 'time', required: true },
      { name: 'endTime', label: 'End time', type: 'time', required: true },
      { name: 'maxBookings', label: 'Max bookings', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'service-images',
    title: 'Service Images',
    description: 'Thumbnail, banner and gallery images for services.',
    endpoint: '/api/service-images',
    idField: 'iMasterId',
    fields: [
      { name: 'iServiceMasterId', label: 'Service', type: 'select', optionSource: 'services', required: true },
      { name: 'imageUrl', label: 'Image URL', type: 'string', required: true },
      {
        name: 'imageType',
        label: 'Image type',
        type: 'enum',
        options: [
          { label: 'Thumbnail', value: 'THUMBNAIL' },
          { label: 'Banner', value: 'BANNER' },
          { label: 'Gallery', value: 'GALLERY' },
        ],
      },
      { name: 'displayOrder', label: 'Display order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'subscription-types',
    title: 'Subscription Types',
    description: 'Reusable subscription plans and duration settings.',
    endpoint: '/api/subscription-types',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'Subscription code', type: 'string', required: true, placeholder: 'MONTHLY_CAR_WASH' },
      { name: 'sName', label: 'Subscription name', type: 'string', required: true, placeholder: 'Monthly Car Wash' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'durationDays', label: 'Duration days', type: 'number', required: true },
      { name: 'discountPercent', label: 'Discount %', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'coupons',
    title: 'Coupons',
    description: 'Discount codes and validity windows.',
    endpoint: '/api/coupons',
    idField: 'iMasterId',
    fields: [
      { name: 'sCode', label: 'Coupon code', type: 'string', required: true, placeholder: 'JIFFIT10' },
      { name: 'sName', label: 'Coupon name', type: 'string', required: true, placeholder: 'Jiffit 10%' },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'discountType',
        label: 'Discount type',
        type: 'enum',
        required: true,
        options: [
          { label: 'Percentage', value: 'PERCENTAGE' },
          { label: 'Flat', value: 'FLAT' },
        ],
      },
      { name: 'discountValue', label: 'Discount value', type: 'number', required: true },
      { name: 'maxDiscountAmount', label: 'Max discount amount', type: 'number' },
      { name: 'minOrderAmount', label: 'Minimum order amount', type: 'number' },
      { name: 'startAt', label: 'Start date', type: 'date', required: true },
      { name: 'endAt', label: 'End date', type: 'date', required: true },
      { name: 'usageLimit', label: 'Usage limit', type: 'number' },
      { name: 'perUserLimit', label: 'Per user limit', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'coupon-service-mappings',
    title: 'Coupon Service Mappings',
    description: 'Restrict coupons to selected services.',
    endpoint: '/api/coupon-service-mappings',
    idField: 'iMasterId',
    fields: [
      { name: 'iCouponMasterId', label: 'Coupon', type: 'select', optionSource: 'coupons', required: true },
      { name: 'iServiceMasterId', label: 'Service', type: 'select', optionSource: 'services', required: true },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'user-addresses',
    title: 'User Addresses',
    description: 'Customer/hero/employee address master.',
    endpoint: '/api/user-addresses',
    idField: 'iMasterId',
    fields: [
      { name: 'iUserMasterId', label: 'User', type: 'select', optionSource: 'users', required: true },
      {
        name: 'addressType',
        label: 'Address type',
        type: 'enum',
        options: [
          { label: 'Home', value: 'HOME' },
          { label: 'Work', value: 'WORK' },
          { label: 'Other', value: 'OTHER' },
        ],
      },
      { name: 'addressLine1', label: 'Address line 1', type: 'string', required: true },
      { name: 'addressLine2', label: 'Address line 2', type: 'string' },
      { name: 'landmark', label: 'Landmark', type: 'string' },
      { name: 'city', label: 'City', type: 'string' },
      { name: 'state', label: 'State', type: 'string' },
      { name: 'pincode', label: 'Pincode', type: 'string' },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'isDefault', label: 'Default address', type: 'boolean' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
  {
    key: 'hero-service-areas',
    title: 'Hero Service Areas',
    description: 'Hero city, pincode and radius coverage.',
    endpoint: '/api/hero-service-areas',
    idField: 'iMasterId',
    fields: [
      { name: 'iHeroUserMasterId', label: 'Hero user', type: 'select', optionSource: 'users', required: true },
      { name: 'city', label: 'City', type: 'string' },
      { name: 'state', label: 'State', type: 'string' },
      { name: 'pincode', label: 'Pincode', type: 'string' },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'radiusKm', label: 'Radius KM', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'boolean' },
    ],
  },
]
